version: "3.9"
services:
    opensearch-server:
        container_name: opensearch-server-benchmarking
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: "1000000000"
        ports:
            - "9201:9200"
            - "9301:9300"
        volumes:
            - ./data/es:/usr/share/elasticsearch/data
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: 8192M
                reservations:
                    cpus: "4"
                    memory: 8192M